# This file is no longer used for deployment
# Each application has its own netlify.toml configuration:
# - Admin Panel: See Admin Panel/netlify.toml
# - Client: See Client/netlify.toml
#
# Please configure Netlify to deploy from the specific application directory
# rather than from the root of the repository.
